Dorion Changelog
SpikeHD/shelter-plugins pull request #10
Opened 2024-01-02 14:53 UTC by luximus-hunter

This PR adds a section to the Dorion settings, giving users a full changelog of previous releases.

> Gets accompanied by [Dorion#183](https://github.com/SpikeHD/Dorion/pull/183)

## Planned features:

- [x] List with all releases and release notes
- [x] Tags for latest and current release
- [x] Images
    - [x] Get image from url
    	- [ ] In JS instead of Rust
    - [x] Cache images so they load faster and not refetch them every page load
- [x] Refresh button (currently refreshes on pageload)
- [x] Update button
- [x] Badge on menu item to indicate update availible

## Screenshot

![image](https://github.com/SpikeHD/shelter-plugins/assets/49814847/28e35c7c-a411-445f-88b5-8cedef323647)

2024-01-02 16:55 UTC, SpikeHD commented
Regarding images, you should be able to do something [like this](https://stackoverflow.com/a/75651388), since the global “window.fetch” method [is overwritten](https://github.com/SpikeHD/Dorion/blob/97be7839cd6747c29093de6574c384d7a464adac/src-tauri/injection/preinject.js#L306) with one that doesn’t have any CORS issues. You’d likely have to write some JS function that goes through each image tag, downloads the image, and then replaces the URL with a new blob URL.

In fact, with that you may be able to omit the current Dorion addition, and just have requests be made through “window.fetch” as well!

2024-01-02 17:20 UTC, luximus-hunter commented
Oh that would be amazing!

2024-01-05 02:19 UTC, SpikeHD requested changes

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +  ui: { injectCss, Header, HeaderTags, showToast, Button, ButtonSizes, ButtonColors, Text, LinkButton },
Just a code style thing, but this many destructed properties should probably be put on their own newlines

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +  setReleases(loadChangelogFromLocalStorage())
Why load from (and save to) localstorage if we are going to load from the internet in a moment anyways? Would probs be better to just display a little loading spinner (or even just centered text that says "Loading...")

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +  async function doUpdate () {
No space between function name and parenthesis please :))

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +    const updateCheck = await invoke('update_check')
Instead of invoking this a second time, we should just store the result of `update_check` as the signal (rather than the `setNeedsUpdate` signal). Eg:

```ts
const [updateCheck, setUpdateCheck] = createSignal<string[]>([])

// ...

createEffect(async () => {
  // ...
  setUpdateCheck(await invoke('update_check'))
  // ...
})

async function doUpdate() {
  invoke('do_update', {
    toUpdate: updateCheck()
  })
}

// ...

return (
  <>
    // ...
    {updateCheck().length > 0 && /* Update banner */}
  </>
)

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +  function sanitizeChangelog(releases: IRelease[]): IRelease[] {
1. This should probably be moved to a util file, maybe `plugins/dorion-settings/util/changelog.ts`? I'm already setting up a util folder there for an unrelated change I am making so it would make sense to put there too
2. A better name for this would probably be `processChangelogElements` since this isn't really sanitation

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +    const changelog: string[] | null = await invoke('get_changelog')
I think I mention this already in the Dorion PR, but do we need to call this from the backend specifically? If this can be done JS-side that would be better, as v3.1.1 users will be able to load the tab (granted, without images) without updating.

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +  async function fetchChangelogFromGitHub(): Promise<IRelease[] | null> {
This should also be moved to a `util/changelog.ts` file, along with the other aforementioned function.

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +      saveChangelogToLocalStorage(changelog)
re: the note I already made about saving/loading from localstorage

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +  async function fixImageLinks(): Promise<void> {
Another function that should be moved to util

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +      const response = await window.fetch(url)
I think a better way to handle this is to do it in parallel using `Promise.all()`. Something like this:

```ts
const images = page.getElementsByTagName('img')

Promise.all(
  images.map(image => {
    const url = image.src
    // etc...
  })
)
```

2024-01-05 02:19 UTC, SpikeHD commented on plugins/dorion-settings/index.tsx
> +  // @ts-expect-error Shelter types are wrong? badgeCount does exist on type
`@uwu/shelter-defs` hasn't seen an update in a while, you're good :P

2024-01-05 02:19 UTC, SpikeHD commented
Good work :) just some relatively minor things!

2024-01-05 11:28 UTC, luximus-hunter commented
i *think* i covered them all.

2024-01-05 16:56 UTC, SpikeHD requested changes

2024-01-05 16:56 UTC, SpikeHD commented on plugins/dorion-settings/components/ChangelogPage.tsx
> +  const [loading ,setLoading] = createSignal<boolean>(true)
Weird comma :P

2024-01-05 16:56 UTC, SpikeHD commented on plugins/dorion-settings/util/changelog.ts
> +async function _fetchChangelogFromGitHub(): Promise<TReleases> {
Functions in Shelter plugins don't need underscores, that's just a Dorion-side thing

2024-01-06 01:25 UTC, merged